Repository JhohannesK/TipoHiZ, pull requests merged in 2024-10, with the labels that each got.

#87 Create SECURITY.md
  SECURITY.md
Labels: enhancement

#106 Resolving BackSpace Issue
  .gitignore
  helpers/utils/useHandleText.ts
  store/actions/WordActions.ts
Labels: hacktoberfest-accepted

#110 fix: reset the test using tab + enter
  components/reset-test-button.tsx
Labels: hacktoberfest-accepted

#109 Themes Addition
  .gitignore
  README.md
  app/layout.tsx
  components/Header.tsx
  components/SvgRender.jsx
  components/expo/theme-choose.tsx
  components/reset-test-button.tsx
  helpers/utils/useHandleText.ts
  store/actions/WordActions.ts
  styles/globals.css
Labels: hacktoberfest-accepted

#123 fixed an issue where i had to add cyberpunk to the themes array in app/layout.tsx
  app/layout.tsx
  components/expo/theme-choose.tsx
  styles/globals.css
Labels: bug, hacktoberfest-accepted

#125 feat(issue-templates): add feature request and bug report templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, hacktoberfest-accepted

#129 Colorcharacter
  components/TextArea.tsx
Labels: new feature, hacktoberfest-accepted

#134 Enhance login signup buttons
  components/Header.tsx
Labels: hacktoberfest-accepted

#148 Fix(docs): Duplicate Section in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#151 ShiftKey Capitalises characters
  helpers/utils/useHandleText.ts
  helpers/utils/useKeydownGetter.ts
Labels: hacktoberfest-accepted

#158 update dep.
  package.json
  pnpm-lock.yaml
Labels: dependencies

#161 (Fixes: #155) Update ESLint configuration to use flat config format
  .eslintrc.json
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: enhancement, hacktoberfest-accepted

#164 Revert "(Fixes: #155) Update ESLint configuration to use flat config format"
  .eslintrc.json
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#146 fixes navbar issues #143
  .github/update-contributors.yml
  components/Footer.tsx
  components/Header.tsx
Labels: hacktoberfest-accepted

#166 Implemented credentials login and register
  .env.example
  .eslintrc.json
  .gitignore
  actions/user.ts
  app/api/auth/[...nextAuth]/route.ts
  app/login/page.tsx
  app/register/page.tsx
  auth.ts
  components/Header.tsx
  lib/db.ts
  models/User.ts
  package.json
  pnpm-lock.yaml
Labels: hacktoberfest-accepted

#154 feat: move prettier dependency to devDependency
  package.json
  pnpm-lock.yaml
Labels: dependencies

#177 Created Pr_template
  .github/pull_request_template.md
Labels: hacktoberfest-accepted

#179 A new chrismas theme added
  app/layout.tsx
  components/expo/theme-choose.tsx
  styles/globals.css
Labels: hacktoberfest-accepted

#181 Feature/issue 138
  app/(Base)/page.tsx
  app/layout.tsx
  components/Header.tsx
  components/Settings.tsx
  store/@types..ts
  store/actions/ConfigActions.ts
  store/index.ts
Labels: hacktoberfest-accepted

#187 fix userSelectPallete gaps and footer border theming
  .husky/pre-commit
  components/Footer.tsx
  components/UserSelectPallete.tsx
Labels: hacktoberfest-accepted

#191 Add correct or wrong color to characters wrt theme
  components/TextArea.tsx
  styles/globals.css
  tailwind.config.js
Labels: enhancement
